version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  test:
    jobs:
      - test
